development:
  adapter: postgresql
  encoding: unicode
  database: todo_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: todo_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: todo_production
  pool: 5
